logging:
  level:
    org:
      springframework: "debug"
spring:
  datasource:
    url: "jdbc:h2:mem:test"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password:
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    jpa:
      show-sql: true
h2:
  console:
    enabled: true
restOperations:
  quoteUri: "https://quoters.apps.pcfone.io/api/random"
